version: '3'
services:

  #PHP Service
  app:
    image: laraws/php:latest
    container_name: convenience_life_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: remote_host=192.168.0.111
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - convenience_life_network

  #Nginx Service
  nginx:
    image: nginx
    container_name: convenience_life_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - convenience_life_network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: convenience_life_db
    restart: unless-stopped
    tty: true
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - convenience_life_network

#Docker Networks
networks:
  convenience_life_network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
